eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://192.9.180.37:8761/eureka/
server:
  port: 8888
  servlet:
    context-path: /snow
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: snow
  datasource:
    name: druidDatasource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?userUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    druid:
      initial-size: 1
      max-active: 100


